import { useState, useEffect } from 'react'

const API_BASE = 'http://localhost:8000'

function MetricCard({ label, value, sub, color = 'text-white' }) {
  return (
    <div className="bg-gray-800/60 border border-gray-700 rounded-xl p-4">
      <p className="text-gray-400 text-xs mb-1">{label}</p>
      <p className={`text-2xl font-bold ${color}`}>{value}</p>
      {sub && <p className="text-gray-500 text-xs mt-1">{sub}</p>}
    </div>
  )
}

function MasteryRow({ item }) {
  const pct = Math.round(item.avg_mastery * 100)
  const color = pct >= 70 ? '#1D9E75' : pct >= 40 ? '#BA7517' : '#E24B4A'
  return (
    <tr className="border-b border-gray-800">
      <td className="py-2 pr-4 text-sm text-gray-300">{item.concept}</td>
      <td className="py-2 pr-4">
        <div className="flex items-center gap-2">
          <div className="flex-1 h-2 bg-gray-700 rounded-full overflow-hidden w-24">
            <div className="h-full rounded-full" style={{ width: `${pct}%`, backgroundColor: color }} />
          </div>
          <span className="text-xs font-mono" style={{ color }}>{pct}%</span>
        </div>
      </td>
      <td className="py-2 text-sm text-red-400">{item.students_below_50pct} students</td>
    </tr>
  )
}

export default function MentorDashboard() {
  const [analytics, setAnalytics] = useState(null)
  const [batch, setBatch] = useState('DSA-Cohort-7')
  const [loading, setLoading] = useState(true)
  const [copied, setCopied] = useState(false)

  const BATCHES = ['DSA-Cohort-7', 'MERN-15', 'MERN-16', 'DSA-8']

  const fetchAnalytics = async () => {
    setLoading(true)
    try {
      const res = await fetch(`${API_BASE}/mentor/analytics?batch_id=${batch}&lecture_id=lecture_007`)
      const data = await res.json()
      setAnalytics(data)
    } catch { }
    setLoading(false)
  }

  useEffect(() => { fetchAnalytics() }, [batch])

  const copyForWhatsapp = () => {
    const text = `📊 Batch ${batch} — Lecture 7 Analysis:\n\n` +
      `🔴 Most confusing: ${analytics?.confusion_peaks?.[0]?.label || 'N/A'} (${analytics?.confusion_peaks?.[0]?.concept || ''})\n` +
      `📉 Weak concept: ${analytics?.low_mastery_concepts?.[0]?.concept || 'N/A'} (${Math.round((analytics?.low_mastery_concepts?.[0]?.avg_mastery || 0) * 100)}% avg mastery)\n\n` +
      `💡 Suggestion: ${analytics?.reexplain_suggestion || ''}\n\n` +
      `Generated by LearnLens 🔍`
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-sheryians-dark flex items-center justify-center">
        <div className="text-center">
          <div className="w-12 h-12 border-2 border-sheryians-orange border-t-transparent rounded-full animate-spin mx-auto mb-4" />
          <p className="text-gray-400">Loading batch analytics...</p>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-sheryians-dark text-white">
      {/* Header */}
      <div className="border-b border-sheryians-border bg-sheryians-card">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="text-sheryians-orange text-2xl font-black tracking-tight">LearnLens</div>
            <span className="bg-amber-500/20 text-amber-400 text-xs px-2 py-1 rounded-full border border-amber-500/30">
              Mentor View
            </span>
          </div>
          <div className="flex items-center gap-3">
            <label className="text-gray-400 text-sm">Batch:</label>
            <select
              value={batch}
              onChange={e => setBatch(e.target.value)}
              className="bg-gray-800 text-white border border-sheryians-border rounded-lg px-3 py-1.5 text-sm focus:outline-none"
            >
              {BATCHES.map(b => <option key={b} value={b}>{b}</option>)}
            </select>
            <a href="/" className="text-gray-400 hover:text-white text-sm underline">← Student View</a>
          </div>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-6 py-8 space-y-6">
        {/* Metric cards */}
        <div className="grid grid-cols-4 gap-4">
          <MetricCard label="Total Students" value={analytics?.total_students || 47} color="text-sheryians-orange" />
          <MetricCard label="Avg Session Length" value={`${analytics?.avg_session_length_min || 38} min`} color="text-blue-400" />
          <MetricCard
            label="Most Confusing Moment"
            value={analytics?.confusion_peaks?.[0]?.label || '—'}
            sub={analytics?.confusion_peaks?.[0]?.concept || ''}
            color="text-red-400"
          />
          <MetricCard
            label="Avg Concept Mastery"
            value={`${Math.round((analytics?.low_mastery_concepts?.[0]?.avg_mastery || 0.45) * 100)}%`}
            color="text-amber-400"
          />
        </div>

        {/* Re-explain suggestion */}
        {analytics?.reexplain_suggestion && (
          <div className="bg-amber-900/20 border border-amber-600/40 rounded-xl p-5">
            <div className="flex items-start justify-between gap-4">
              <div className="flex items-start gap-3">
                <span className="text-2xl">💡</span>
                <div>
                  <h3 className="text-amber-400 font-semibold mb-1">Re-Explain Suggestion for Tomorrow</h3>
                  <p className="text-amber-200 text-sm leading-relaxed">{analytics.reexplain_suggestion}</p>
                </div>
              </div>
              <button
                onClick={copyForWhatsapp}
                className="flex-shrink-0 bg-green-600 hover:bg-green-500 text-white text-sm font-medium px-4 py-2 rounded-lg transition-colors whitespace-nowrap"
              >
                {copied ? '✅ Copied!' : '📱 Copy for WhatsApp'}
              </button>
            </div>
          </div>
        )}

        <div className="grid grid-cols-2 gap-6">
          {/* Confusion peaks */}
          <div className="bg-sheryians-card border border-sheryians-border rounded-xl p-5">
            <h3 className="text-white font-semibold mb-4 flex items-center gap-2">
              <span>🔥</span> Confusion Peaks
              <span className="text-xs text-gray-500 font-normal">— Students who rewound here</span>
            </h3>
            {(analytics?.confusion_peaks || []).length === 0 ? (
              <p className="text-gray-500 text-sm">No confusion peaks detected yet</p>
            ) : (
              <div className="space-y-3">
                {(analytics?.confusion_peaks || []).map((peak, i) => (
                  <div key={i} className="flex items-center gap-3">
                    <span className="font-mono text-red-400 text-sm w-12">{peak.label}</span>
                    <div className="flex-1 h-6 bg-gray-700 rounded overflow-hidden">
                      <div
                        className="h-full bg-red-500/70 rounded flex items-center px-2"
                        style={{ width: `${Math.min(100, (peak.rewind_count / 50) * 100)}%` }}
                      >
                        <span className="text-white text-xs font-bold">{peak.rewind_count}</span>
                      </div>
                    </div>
                    <span className="text-xs text-gray-500 w-24">{peak.concept}</span>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Top questions */}
          <div className="bg-sheryians-card border border-sheryians-border rounded-xl p-5">
            <h3 className="text-white font-semibold mb-1 flex items-center gap-2">
              <span>❓</span> Top Batch Questions
            </h3>
            <p className="text-gray-500 text-xs mb-4">Cover these in tomorrow's doubt session</p>
            <div className="space-y-2">
              {(analytics?.top_questions || []).map((q, i) => (
                <div key={i} className="flex items-start gap-2 p-2 bg-gray-800/50 rounded-lg">
                  <span className="text-sheryians-orange font-bold text-sm mt-0.5">{q.count}x</span>
                  <p className="text-gray-300 text-sm flex-1">{q.question}</p>
                </div>
              ))}
              {(analytics?.top_questions || []).length === 0 && (
                <p className="text-gray-500 text-sm">No questions logged yet</p>
              )}
            </div>
          </div>
        </div>

        {/* Concept mastery table */}
        <div className="bg-sheryians-card border border-sheryians-border rounded-xl p-5">
          <h3 className="text-white font-semibold mb-4 flex items-center gap-2">
            <span>📊</span> Concept Mastery by Batch
          </h3>
          {(analytics?.low_mastery_concepts || []).length === 0 ? (
            <p className="text-gray-500 text-sm">All concepts well mastered! 🎉</p>
          ) : (
            <table className="w-full">
              <thead>
                <tr className="text-gray-500 text-xs border-b border-gray-700">
                  <th className="text-left pb-2 pr-4">Concept</th>
                  <th className="text-left pb-2 pr-4">Avg Mastery</th>
                  <th className="text-left pb-2">Below 50%</th>
                </tr>
              </thead>
              <tbody>
                {analytics.low_mastery_concepts.map((item, i) => <MasteryRow key={i} item={item} />)}
              </tbody>
            </table>
          )}
        </div>
      </div>
    </div>
  )
}